GENOME_IDX:
    - "/home/groups/hoolock2/u0/genomes/ucsc/hg38/indexes/bowtie2/hg38"
SAMPLES:
    - 'A1_H3K27Ac_S22'
    - 'A2_H3K4me1_S7'
    - 'AG2_H3K4me1_S15'
    - 'AG1_H3K4me1_S13'
    - 'AG2_H3K27Ac_S32'
    - 'AG1_H3K27Ac_S30'
    - 'A2_H3K4me3_S8'
    - 'A1_IgG_S21'
    - 'AG2_IgG_S31'
    - 'AG1_H3K4me3_S14'
    - 'A2_H3K27Ac_S24'
    - 'AG1_IgG_S29'
    - 'A1_H3K4me3_S6'
    - 'A2_IgG_S23'
    - 'A1_H3K4me1_S5'
    - 'AG2_H3K4me3_S16'
