GENOME_IDX:
    - "/home/groups/hoolock2/u0/genomes/ucsc/hg38/indexes/bowtie2/hg38"
SAMPLES:
    - "A1_H3K27Ac_Kasumi_S22"
    - "A1_H3K4me1_Kasumi_S5"
    - "A1_H3K4me3_Kasumi_S6"
    - "A1_IgG_Kasumi_S21"
    - "A2_H3K27Ac_Kasumi_S24"
    - "A2_H3K4me1_Kasumi_S7"
    - "A2_H3K4me3_Kasumi_S8"
    - "A2_IgG_Kasumi_S23"
    - "AG1_H3K27Ac_Kasumi_S30"
    - "AG1_H3K4me1_Kasumi_S13"
    - "AG1_H3K4me3_Kasumi_S14"
    - "AG1_IgG_Kasumi_S29"
    - "AG2_H3K27Ac_Kasumi_S32"
    - "AG2_H3K4me1_Kasumi_S15"
    - "AG2_H3K4me3_Kasumi_S16"
    - "AG2_IgG_Kasumi_S31"
    - "G1_H3K27Ac_Kasumi_S26"
    - "G1_H3K4me1_Kasumi_S9"
    - "G1_H3K4me3_Kasumi_S10"
    - "G1_IgG_Kasumi_S25"
    - "G2_H3K27Ac_Kasumi_S28"
    - "G2_H3K4me1_Kasumi_S11"
    - "G2_H3K4me3_Kasumi_S12"
    - "G2_IgG_Kasumi_S27"
    - "ND1_H3K27Ac_Kasumi_S18"
    - "ND1_H3K4me1_Kasumi_S1"
    - "ND1_H3K4me3_Kasumi_S2"
    - "ND1_IgG_Kasumi_S17"
    - "ND2_H3K27Ac_Kasumi_S20"
    - "ND2_H3K4me1_Kasumi_S3"
    - "ND2_H3K4me3_Kasumi_S4"
    - "ND2_IgG_Kasumi_S19"
