GENOME_IDX:
    - "/path/to/bowtie2/index/"
CHRSIZES:
    - "/path/to/genome/chrom.sizes/"
SAMPLES:
    # samples for the experiment
    # names must be part of fastq file
    # SAMPLE_1_R1.fastq.gz, and 
    # SAMPLE_1_R2.fastq.gz are assumed to be
    # found at path: data/raw
    - "SAMPLE_1"
    - "SAMPLE_2"
    - "SAMPLE_3"
    - "SAMPLE_4" 
MACS2:
    # the -g for genome size parameter in MACS2
    G:
      - "hs"  # or "hs" for human  
     
